/**
 * Generate the provider wire types in `src/generated/` from the specs in `specs/`
 * (`docs/adr/0012`). Offline; runs locally:
 *
 *   pnpm gen:api-types           # idempotent — a second run leaves `git status` clean
 *
 * A vendored spec is pruned to the operations the Worker calls (`operationIds`) with Redocly's
 * `filter-in` decorator plus `removeUnusedComponents`, so the generated file only carries what
 * the adapters use and a spec refresh diffs small. The hand-written OAuth fragments are generated
 * whole. To call a new endpoint, add its `operationId` here and rerun.
 */
import { mkdir, readFile, writeFile } from "node:fs/promises";
import {
  BaseResolver,
  bundleDocument,
  createConfig,
  makeDocumentFromString,
} from "@redocly/openapi-core";
import openapiTS, { astToString, COMMENT_HEADER } from "openapi-typescript";

interface Target {
  spec: string;
  out: string;
  /** Keep only these operations; omitted = the whole document. */
  operationIds?: string[];
}

const TARGETS: Target[] = [
  {
    spec: "specs/google-calendar-v3.openapi.json",
    out: "src/generated/google-calendar-v3.d.ts",
    operationIds: [
      "calendar.events.list",
      "calendar.events.get",
      "calendar.events.watch",
      "calendar.channels.stop",
    ],
  },
  {
    spec: "specs/zoom-meetings.openapi.json",
    out: "src/generated/zoom-meetings.d.ts",
    operationIds: ["meetingInviteLinksCreate"],
  },
  { spec: "specs/google-oauth-token.openapi.json", out: "src/generated/google-oauth-token.d.ts" },
  { spec: "specs/zoom-oauth-token.openapi.json", out: "src/generated/zoom-oauth-token.d.ts" },
];

const HTTP_METHODS = ["get", "put", "post", "delete", "options", "head", "patch", "trace"];

/** Keep `operationIds` (and the components they reach); drop path items left without a method. */
async function prune(raw: string, spec: string, operationIds: string[]): Promise<object> {
  const config = await createConfig(
    { decorators: { "filter-in": { property: "operationId", value: operationIds } } },
    { extends: ["minimal"] },
  );
  const result = await bundleDocument({
    document: makeDocumentFromString(raw, spec),
    config: config.styleguide,
    externalRefResolver: new BaseResolver(),
    removeUnusedComponents: true,
    dereference: false,
  });
  const problems = result.problems.filter((p) => p.severity === "error");
  if (problems.length > 0) {
    throw new Error(`${spec}: ${problems.map((p) => p.message).join("; ")}`);
  }
  const doc = result.bundle.parsed as { paths: Record<string, Record<string, unknown>> };
  // `filter-in` empties path items whose operations were all removed but keeps the shell when
  // the item has path-level `parameters` (Google's do).
  doc.paths = Object.fromEntries(
    Object.entries(doc.paths).filter(([, item]) => HTTP_METHODS.some((m) => m in item)),
  );
  return doc;
}

await mkdir("src/generated", { recursive: true });
for (const target of TARGETS) {
  const raw = await readFile(target.spec, "utf8");
  const doc = target.operationIds
    ? await prune(raw, target.spec, target.operationIds)
    : (JSON.parse(raw) as object);
  const ast = await openapiTS(doc, { defaultNonNullable: false, alphabetize: true });
  const banner = `// Generated by scripts/gen-api-types.ts from ${target.spec} — do not edit; run \`pnpm gen:api-types\`.\n`;
  await writeFile(target.out, `${banner}${COMMENT_HEADER}${astToString(ast)}`);
  console.log(`${target.out} ← ${target.spec}`);
}
